# Generated by Django 5.0.4 on 2026-05-26 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('input_mode', models.CharField(choices=[('paste', 'Paste'), ('file', 'File Upload'), ('github', 'GitHub URL')], max_length=10)),
                ('language', models.CharField(default='Unknown', max_length=50)),
                ('raw_code', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('agent_results', models.JSONField(default=dict)),
                ('synthesis', models.JSONField(default=dict)),
                ('event_log', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('share_slug', models.SlugField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_reviews',
                'ordering': ['-saved_at'],
            },
        ),
    ]
